-- OpenRIN_Services: semilla de textos de localización (generada desde los .resx del proyecto).
-- Regenerable con PPDD/tools/generar_seed_textos.py — MERGE idempotente por (idioma, clave).
-- IMPORTANTE: importar SIEMPRE con la bandera UTF-8:  sqlcmd -f 65001 -i localizacion_seed.sql

-- Idioma es: 303 claves
MERGE dbo.Textos AS destino
USING (VALUES
    ('es', 'agenda.actualizar', N'Actualizar agenda'),
    ('es', 'agenda.agendar', N'Agendar turno'),
    ('es', 'agenda.columna.fechaHora', N'Fecha y hora'),
    ('es', 'agenda.columna.medico', N'Médico'),
    ('es', 'agenda.columna.observaciones', N'Observaciones'),
    ('es', 'agenda.desde', N'Desde:'),
    ('es', 'agenda.escalar', N'¿Escalar la decisión al médico? (rechazo por duda clínica)'),
    ('es', 'agenda.estado.atendido', N'Atendido'),
    ('es', 'agenda.estado.cancelado', N'Cancelado'),
    ('es', 'agenda.estado.confirmado', N'Confirmado'),
    ('es', 'agenda.estado.pendiente', N'Pendiente'),
    ('es', 'agenda.estado.reasignacion', N'En reasignación'),
    ('es', 'agenda.hasta', N'Hasta:'),
    ('es', 'agenda.hora', N'Hora'),
    ('es', 'agenda.motivoRechazo', N'Motivo del rechazo'),
    ('es', 'agenda.reasignacionOk', N'Reasignación realizada. Notificaciones registradas:'),
    ('es', 'agenda.rechazar', N'Rechazar'),
    ('es', 'agenda.selSugerencia', N'Seleccione una sugerencia de la lista.'),
    ('es', 'agenda.sinMedicos', N'No hay médicos habilitados; contacte al administrador.'),
    ('es', 'agenda.sinTurnos', N'Sin turnos en el período seleccionado.'),
    ('es', 'agenda.sug.columna.a', N'A (crítico)'),
    ('es', 'agenda.sug.columna.de', N'De (estable)'),
    ('es', 'agenda.sugerencias', N'Sugerencias de reasignación'),
    ('es', 'agenda.sugerenciasVacias', N'Sin sugerencias por ahora.'),
    ('es', 'app.nombre', N'OpenRIN'),
    ('es', 'app.titulo', N'Plataforma Integral de Alertas y Monitoreo'),
    ('es', 'comun.aceptar', N'Aceptar'),
    ('es', 'comun.buscar', N'Buscar'),
    ('es', 'comun.cancelar', N'Cancelar'),
    ('es', 'comun.cargando', N'Cargando...'),
    ('es', 'comun.cerrar', N'Cerrar'),
    ('es', 'comun.eliminar', N'Eliminar'),
    ('es', 'comun.guardar', N'Guardar'),
    ('es', 'comun.modificar', N'Modificar'),
    ('es', 'comun.no', N'No'),
    ('es', 'comun.nuevo', N'Nuevo'),
    ('es', 'comun.salir', N'Salir'),
    ('es', 'comun.si', N'Sí'),
    ('es', 'comun.volver', N'Volver'),
    ('es', 'error.contacto', N'Si el problema persiste, contacte al administrador del sistema.'),
    ('es', 'error.generico', N'Ocurrió un error inesperado. La operación no pudo completarse.'),
    ('es', 'error.titulo', N'Error'),
    ('es', 'eventos.columna.accion', N'Acción tomada'),
    ('es', 'eventos.columna.gravedad', N'Gravedad'),
    ('es', 'eventos.columna.tipo', N'Tipo de evento'),
    ('es', 'eventos.fechaEvento', N'Fecha del evento'),
    ('es', 'eventos.gravedad.grave', N'Grave'),
    ('es', 'eventos.gravedad.leve', N'Leve'),
    ('es', 'eventos.gravedad.moderada', N'Moderada'),
    ('es', 'eventos.recientes', N'Últimos eventos registrados'),
    ('es', 'eventos.registrar', N'Registrar evento adverso'),
    ('es', 'eventos.selPaciente', N'Busque un paciente para registrar un evento.'),
    ('es', 'eventos.sinEventos', N'Sin eventos registrados.'),
    ('es', 'eventos.tipo.hemorragia', N'Hemorragia'),
    ('es', 'eventos.tipo.otro', N'Otro'),
    ('es', 'eventos.tipo.reaccion', N'Reacción adversa'),
    ('es', 'eventos.tipo.trombosis', N'Trombosis'),
    ('es', 'hc.diagnostico', N'Diagnóstico / indicación'),
    ('es', 'hc.dosis', N'Dosis'),
    ('es', 'hc.limiteInferior', N'Límite inferior del RIN'),
    ('es', 'hc.limiteSuperior', N'Límite superior del RIN'),
    ('es', 'hc.medicamento', N'Medicamento'),
    ('es', 'hc.periodicidad', N'Periodicidad de reporte (días)'),
    ('es', 'hc.proximoControl', N'Programar próximo control'),
    ('es', 'hc.sinConfigurar', N'El paciente no posee historia clínica configurada todavía.'),
    ('es', 'hc.sinDiagnostico', N'(Sin diagnóstico)'),
    ('es', 'hc.soloLectura', N'Vista de solo lectura: su perfil no permite modificar la historia clínica.'),
    ('es', 'hc.titulo', N'Historia Clínica Hematológica'),
    ('es', 'idioma.en', N'English (United States)'),
    ('es', 'idioma.es', N'Español (Latinoamérica)'),
    ('es', 'idioma.zh-CN', N'中文（简体）'),
    ('es', 'idiomas.agregar', N'Agregar leyenda'),
    ('es', 'idiomas.clave', N'Clave'),
    ('es', 'idiomas.claveObligatoria', N'Ingrese la clave de la leyenda.'),
    ('es', 'idiomas.codigo', N'Código:'),
    ('es', 'idiomas.confirmarEliminar', N'¿Eliminar el idioma seleccionado y todas sus leyendas?'),
    ('es', 'idiomas.eliminar', N'Eliminar idioma'),
    ('es', 'idiomas.guardadoOk', N'Cambios guardados. Las vistas se actualizaron en caliente.'),
    ('es', 'idiomas.guardar', N'Guardar cambios'),
    ('es', 'idiomas.nombre', N'Nombre:'),
    ('es', 'idiomas.nuevo', N'Nuevo idioma'),
    ('es', 'idiomas.sinSeleccion', N'Seleccione un idioma.'),
    ('es', 'idiomas.valor', N'Valor'),
    ('es', 'integridad.alerta', N'⚠ Integridad:'),
    ('es', 'integridad.mensaje', N'Se detectaron problemas de integridad en la base de datos:'),
    ('es', 'integridad.ok', N'🛡️ Integridad OK'),
    ('es', 'integridad.titulo', N'Integridad de datos'),
    ('es', 'integridad.vulnerada.detalle', N'Detalle técnico de la verificación:'),
    ('es', 'integridad.vulnerada.mensaje', N'La verificación de integridad detectó alteraciones en la base de datos realizadas por fuera del sistema. Se bloqueó el acceso y se requiere la intervención del administrador con urgencia.'),
    ('es', 'integridad.vulnerada.salir', N'Salir'),
    ('es', 'integridad.vulnerada.sinConexion', N'No se pudo ejecutar la verificación de integridad (¿base de datos inaccesible?). Contacte al administrador.'),
    ('es', 'integridad.vulnerada.titulo', N'Base de datos vulnerada'),
    ('es', 'login.bienvenida', N'Bienvenido/a'),
    ('es', 'login.campoObligatorio', N'Complete usuario y contraseña.'),
    ('es', 'login.contrasena', N'Contraseña'),
    ('es', 'login.errorBloqueado', N'Cuenta bloqueada temporalmente por seguridad.'),
    ('es', 'login.errorCredenciales', N'Usuario o contraseña incorrectos.'),
    ('es', 'login.errorInhabilitado', N'El usuario no está habilitado. Contacte al administrador.'),
    ('es', 'login.idioma', N'Idioma'),
    ('es', 'login.ingresar', N'Ingresar'),
    ('es', 'login.olvidoContrasena', N'¿Olvidó su contraseña?'),
    ('es', 'login.recuperar.enviar', N'Validar respuesta'),
    ('es', 'login.recuperar.respuesta', N'Respuesta de seguridad'),
    ('es', 'login.recuperar.titulo', N'Recuperar Contraseña'),
    ('es', 'login.titulo', N'Iniciar Sesión'),
    ('es', 'login.usuario', N'Usuario'),
    ('es', 'mod.agenda', N'Agenda y Turnos'),
    ('es', 'mod.eventos', N'Eventos Adversos'),
    ('es', 'mod.pacientes', N'Pacientes e Historias Clínicas'),
    ('es', 'mod.portal', N'Portal del Paciente'),
    ('es', 'mod.reportes', N'Reportes'),
    ('es', 'mod.rin', N'Recepción de RIN'),
    ('es', 'mod.seguimiento', N'Seguimiento Clínico'),
    ('es', 'mod.sistema', N'Sistema y Bitácora'),
    ('es', 'pacientes.alta', N'Alta de Paciente'),
    ('es', 'pacientes.baja', N'Dar de baja'),
    ('es', 'pacientes.baja.confirmar', N'¿Confirmar la baja de ''{0}''? Se deshabilitarán sus credenciales del portal (el historial clínico se conserva).'),
    ('es', 'pacientes.baja.motivo', N'Motivo de la baja'),
    ('es', 'pacientes.buscar', N'Buscar:'),
    ('es', 'pacientes.buscarPlaceholder', N'Nombre o documento...'),
    ('es', 'pacientes.cred.aviso', N'Entregue estas credenciales al paciente. La contraseña temporal no volverá a mostrarse.'),
    ('es', 'pacientes.cred.copiado', N'Contraseña copiada al portapapeles.'),
    ('es', 'pacientes.cred.copiar', N'Copiar contraseña'),
    ('es', 'pacientes.cred.titulo', N'Credenciales del portal generadas'),
    ('es', 'pacientes.documento', N'Documento (DNI)'),
    ('es', 'pacientes.email', N'Correo electrónico'),
    ('es', 'pacientes.estado', N'Estado'),
    ('es', 'pacientes.estadoActivo', N'Activo'),
    ('es', 'pacientes.estadoInactivo', N'Inactivo'),
    ('es', 'pacientes.fechaAlta', N'Fecha de alta'),
    ('es', 'pacientes.historia', N'Historia clínica'),
    ('es', 'pacientes.nombre', N'Nombre completo'),
    ('es', 'pacientes.numeroAfiliado', N'N° de afiliado'),
    ('es', 'pacientes.obraSocial', N'Obra social'),
    ('es', 'pacientes.resultados', N'{0} paciente(s) encontrado(s)'),
    ('es', 'pacientes.sinObraSocial', N'(Sin obra social)'),
    ('es', 'pacientes.sinSeleccion', N'Seleccione un paciente de la lista.'),
    ('es', 'pacientes.telefono', N'Teléfono'),
    ('es', 'pacientes.titulo', N'Gestión de Pacientes'),
    ('es', 'pacientes.verInactivos', N'Ver inactivos'),
    ('es', 'panel.actualizar', N'Actualizar'),
    ('es', 'panel.columna.alerta', N'Alerta'),
    ('es', 'panel.columna.criticidad', N'Criticidad'),
    ('es', 'panel.columna.dias', N'Días sin reportar'),
    ('es', 'panel.columna.documento', N'Documento'),
    ('es', 'panel.columna.fecha', N'Último reporte'),
    ('es', 'panel.columna.paciente', N'Paciente'),
    ('es', 'panel.columna.ultimoRin', N'Último RIN'),
    ('es', 'panel.criticidadAlta', N'Crítico (Alta)'),
    ('es', 'panel.criticidadBaja', N'Estable (Baja)'),
    ('es', 'panel.criticidadMedia', N'Moderado (Media)'),
    ('es', 'panel.leyenda', N'Leyenda:'),
    ('es', 'panel.refresco', N'Actualizado:'),
    ('es', 'panel.sinDatos', N'Sin datos'),
    ('es', 'panel.titulo', N'Panel de Monitoreo'),
    ('es', 'portal.bienvenida', N'Hola,'),
    ('es', 'portal.enviar', N'Enviar reporte'),
    ('es', 'portal.gracias', N'¡Gracias! Su reporte quedó registrado.'),
    ('es', 'portal.historial', N'Mi historial clínico'),
    ('es', 'portal.notificado', N'El equipo médico fue notificado y revisará su caso.'),
    ('es', 'portal.reportar', N'Reportar mi RIN'),
    ('es', 'portal.sinVinculo', N'Su cuenta no está vinculada a un paciente del centro. Contacte a la administración.'),
    ('es', 'rec.cambiar', N'Cambiar contraseña'),
    ('es', 'rec.nuevaContrasena', N'Nueva contraseña'),
    ('es', 'rec.ok', N'¡Listo! La contraseña fue actualizada. Ya puede iniciar sesión con la nueva.'),
    ('es', 'rec.pregunta', N'Pregunta de seguridad:'),
    ('es', 'rec.pregunta1', N'¿Ciudad donde creció?'),
    ('es', 'rec.pregunta2', N'¿Nombre de su primera mascota?'),
    ('es', 'rec.pregunta3', N'¿Nombre de su escuela primaria?'),
    ('es', 'rec.respuesta', N'Respuesta'),
    ('es', 'rec.sinPregunta', N'No se pudo obtener una pregunta de seguridad para ese usuario. Contacte al administrador.'),
    ('es', 'rec.titulo', N'Recuperación de contraseña'),
    ('es', 'rec.verPregunta', N'Ver pregunta de seguridad'),
    ('es', 'reportes.bajoDesempeno', N'⚠ BAJO DESEMPEÑO'),
    ('es', 'reportes.clas.deficiente', N'Deficiente'),
    ('es', 'reportes.clas.optimo', N'Óptimo'),
    ('es', 'reportes.clas.suboptimo', N'Subóptimo'),
    ('es', 'reportes.columna.clasificacion', N'Clasificación'),
    ('es', 'reportes.columna.descripcion', N'Descripción'),
    ('es', 'reportes.columna.diagnostico', N'Diagnóstico'),
    ('es', 'reportes.columna.indicador', N'Indicador prom. (%)'),
    ('es', 'reportes.columna.mediciones', N'Mediciones'),
    ('es', 'reportes.columna.pacientes', N'Pacientes'),
    ('es', 'reportes.columna.porcentaje', N'% en rango'),
    ('es', 'reportes.columna.tipo', N'Tipo'),
    ('es', 'reportes.diagnostico', N'Por diagnóstico'),
    ('es', 'reportes.exportadoOk', N'Exportación registrada. Archivo generado:'),
    ('es', 'reportes.exportar', N'Exportar historial'),
    ('es', 'reportes.formato', N'Formato:'),
    ('es', 'reportes.generar', N'Ver reporte del mes'),
    ('es', 'reportes.generarDiag', N'Generar reporte'),
    ('es', 'reportes.historial', N'Historial del paciente'),
    ('es', 'reportes.historialVacio', N'Busque un paciente para ver su historial unificado.'),
    ('es', 'reportes.indicadorGlobal', N'Indicador global de eficacia'),
    ('es', 'reportes.mensual', N'Reporte mensual'),
    ('es', 'reportes.pacientesDatos', N'Pacientes con datos:'),
    ('es', 'reportes.periodo', N'Período:'),
    ('es', 'reportes.sinItems', N'sin registros aún'),
    ('es', 'reportes.sinMediciones', N'Sin mediciones:'),
    ('es', 'reportes.sinReporte', N'Genere el reporte del mes para ver los indicadores.'),
    ('es', 'rin.alertaGenerada', N'🔔 Alerta urgente generada y notificada (médico y administrativo).'),
    ('es', 'rin.canal', N'Canal de reporte'),
    ('es', 'rin.canal.digital', N'Digital (portal)'),
    ('es', 'rin.canal.telefonico', N'Telefónico (carga manual)'),
    ('es', 'rin.columna.canal', N'Canal'),
    ('es', 'rin.columna.fecha', N'Fecha'),
    ('es', 'rin.columna.valor', N'Valor'),
    ('es', 'rin.enviado', N'Su RIN fue reportado correctamente.'),
    ('es', 'rin.fecha', N'Fecha de medición'),
    ('es', 'rin.historial', N'Últimas mediciones'),
    ('es', 'rin.identificacion', N'Identificación del paciente (DNI):'),
    ('es', 'rin.pacienteInactivo', N'El paciente está dado de baja; no admite nuevos reportes.'),
    ('es', 'rin.pacienteNoEncontrado', N'No se encontró un paciente con ese documento.'),
    ('es', 'rin.rango', N'Rango terapéutico'),
    ('es', 'rin.reportar', N'Reportar RIN'),
    ('es', 'rin.resultado', N'Resultado del triaje'),
    ('es', 'rin.resultadoSinDatos', N'Busque un paciente y cargue un valor de RIN.'),
    ('es', 'rin.sinHistoria', N'El paciente no posee historia clínica configurada (necesaria para el triaje).'),
    ('es', 'rin.sinMediciones', N'Sin mediciones previas.'),
    ('es', 'rin.tendencia', N'⚠ Reclasificado por tendencia peligrosa (±0.1 en dos reportes consecutivos).'),
    ('es', 'rin.ultimaMedicion', N'Última medición'),
    ('es', 'rin.valor', N'Valor de RIN'),
    ('es', 'seguimiento.columna.decision', N'Decisión'),
    ('es', 'seguimiento.columna.diasVencido', N'Días vencidos'),
    ('es', 'seguimiento.columna.intentos', N'Intentos'),
    ('es', 'seguimiento.columna.protocolo', N'Protocolo'),
    ('es', 'seguimiento.columna.ultimoReporte', N'Último reporte'),
    ('es', 'seguimiento.contacto', N'Registrar intento de contacto'),
    ('es', 'seguimiento.contacto.correo', N'Correo electrónico'),
    ('es', 'seguimiento.contacto.llamado', N'Llamado telefónico'),
    ('es', 'seguimiento.contacto.mensaje', N'Mensaje de texto'),
    ('es', 'seguimiento.contacto.otro', N'Otro'),
    ('es', 'seguimiento.contactoOk', N'Contacto exitoso: la alerta de ausencia quedó cerrada.'),
    ('es', 'seguimiento.dec.contactar', N'Contactar personalmente'),
    ('es', 'seguimiento.dec.nocontactable', N'Declarar no contactable'),
    ('es', 'seguimiento.dec.periodicidad', N'Cambiar periodicidad'),
    ('es', 'seguimiento.dec.visita', N'Programar visita domiciliaria'),
    ('es', 'seguimiento.decSinIntentos', N'La decisión clínica requiere al menos un intento de contacto registrado.'),
    ('es', 'seguimiento.decision', N'Decisión clínica'),
    ('es', 'seguimiento.decisionOk', N'Decisión registrada; la alerta de ausencia quedó resuelta.'),
    ('es', 'seguimiento.detalleDecision', N'Detalle de la decisión'),
    ('es', 'seguimiento.detalleVacio', N'Seleccione un caso de la lista.'),
    ('es', 'seguimiento.deteccion', N'Detección completada. Casos nuevos:'),
    ('es', 'seguimiento.detectar', N'Detectar plazos vencidos'),
    ('es', 'seguimiento.escalada', N'Escalada al médico'),
    ('es', 'seguimiento.escaladaMsg', N'Se alcanzó el umbral de 3 intentos fallidos: el caso fue ESCALADO al médico para su decisión clínica.'),
    ('es', 'seguimiento.historial', N'Historial del caso'),
    ('es', 'seguimiento.intentoRegistrado', N'Intento registrado.'),
    ('es', 'seguimiento.nuevaPeriodicidad', N'Nueva periodicidad (días)'),
    ('es', 'seguimiento.protocolo.enCurso', N'En curso'),
    ('es', 'seguimiento.protocolo.escalada', N'ESCALADA AL MÉDICO'),
    ('es', 'seguimiento.registrarDecision', N'Registrar decisión'),
    ('es', 'seguimiento.registrarIntento', N'Registrar intento'),
    ('es', 'seguimiento.resultado', N'Resultado'),
    ('es', 'seguimiento.resultado.exitoso', N'Exitoso (cierra la alerta)'),
    ('es', 'seguimiento.resultado.fallido', N'Fallido (suma intento)'),
    ('es', 'seguimiento.sinPendientes', N'Sin seguimientos pendientes. Use «Detectar plazos vencidos» para buscar casos nuevos.'),
    ('es', 'seguimiento.tipoContacto', N'Tipo de contacto'),
    ('es', 'shell.cerrarSesion', N'Cerrar sesión'),
    ('es', 'shell.confirmarCerrar', N'¿Desea cerrar la sesión actual?'),
    ('es', 'shell.enConstruccion', N'Módulo en construcción; estará disponible en el próximo avance.'),
    ('es', 'shell.modulos', N'Módulos'),
    ('es', 'shell.seleccione', N'Seleccione un módulo del menú lateral para comenzar.'),
    ('es', 'shell.sesion', N'Sesión:'),
    ('es', 'shell.titulo', N'Panel Principal'),
    ('es', 'sistema.actualizar', N'Actualizar'),
    ('es', 'sistema.bitacora', N'Bitácora'),
    ('es', 'sistema.cambios', N'Control de cambios'),
    ('es', 'sistema.cambios.anterior', N'Estado anterior (JSON)'),
    ('es', 'sistema.cambios.buscar', N'Buscar historial'),
    ('es', 'sistema.cambios.columna.entidad', N'Entidad'),
    ('es', 'sistema.cambios.columna.registro', N'Registro'),
    ('es', 'sistema.cambios.columna.tipo', N'Tipo'),
    ('es', 'sistema.cambios.confirmar', N'¿Recomponer el estado anterior del registro seleccionado?'),
    ('es', 'sistema.cambios.entidad', N'Entidad:'),
    ('es', 'sistema.cambios.idRegistro', N'N.º de registro:'),
    ('es', 'sistema.cambios.nuevo', N'Estado nuevo (JSON)'),
    ('es', 'sistema.cambios.restaurar', N'Restaurar estado anterior'),
    ('es', 'sistema.cambios.selCambio', N'Seleccione un cambio del historial.'),
    ('es', 'sistema.cambios.sinId', N'El número de registro debe ser numérico.'),
    ('es', 'sistema.cambios.todas', N'Todas las entidades'),
    ('es', 'sistema.columna.activo', N'Activo'),
    ('es', 'sistema.columna.bloqueado', N'Bloqueado hasta'),
    ('es', 'sistema.columna.capa', N'Capa'),
    ('es', 'sistema.columna.intentos', N'Intentos'),
    ('es', 'sistema.columna.mensaje', N'Mensaje'),
    ('es', 'sistema.columna.nivel', N'Nivel'),
    ('es', 'sistema.columna.nombre', N'Nombre completo'),
    ('es', 'sistema.columna.perfil', N'Perfil'),
    ('es', 'sistema.columna.usuario', N'Usuario'),
    ('es', 'sistema.confirmarDeshabilitar', N'¿Deshabilitar las credenciales del usuario seleccionado?'),
    ('es', 'sistema.confirmarHabilitar', N'¿Habilitar las credenciales del usuario seleccionado?'),
    ('es', 'sistema.deshabilitar', N'Deshabilitar'),
    ('es', 'sistema.habilitar', N'Habilitar'),
    ('es', 'sistema.idiomas', N'Idiomas'),
    ('es', 'sistema.nivel', N'Nivel mínimo:'),
    ('es', 'sistema.nivel.todos', N'Todos'),
    ('es', 'sistema.no', N'No'),
    ('es', 'sistema.nuevoUsuario', N'Nuevo usuario'),
    ('es', 'sistema.selUsuario', N'Seleccione un usuario de la lista.'),
    ('es', 'sistema.si', N'Sí'),
    ('es', 'sistema.usuarioRegistrado', N'Usuario registrado correctamente.'),
    ('es', 'sistema.usuarios', N'Usuarios')
) AS origen(CodigoIdioma, Clave, Valor)
ON destino.CodigoIdioma = origen.CodigoIdioma AND destino.Clave = origen.Clave
WHEN MATCHED THEN UPDATE SET Valor = origen.Valor
WHEN NOT MATCHED THEN INSERT (CodigoIdioma, Clave, Valor)
    VALUES (origen.CodigoIdioma, origen.Clave, origen.Valor);
GO

-- Idioma en: 303 claves
MERGE dbo.Textos AS destino
USING (VALUES
    ('en', 'agenda.actualizar', N'Refresh schedule'),
    ('en', 'agenda.agendar', N'Schedule appointment'),
    ('en', 'agenda.columna.fechaHora', N'Date & time'),
    ('en', 'agenda.columna.medico', N'Physician'),
    ('en', 'agenda.columna.observaciones', N'Notes'),
    ('en', 'agenda.desde', N'From:'),
    ('en', 'agenda.escalar', N'Escalate the decision to the physician? (rejection due to clinical doubt)'),
    ('en', 'agenda.estado.atendido', N'Attended'),
    ('en', 'agenda.estado.cancelado', N'Cancelled'),
    ('en', 'agenda.estado.confirmado', N'Confirmed'),
    ('en', 'agenda.estado.pendiente', N'Pending'),
    ('en', 'agenda.estado.reasignacion', N'Under reassignment'),
    ('en', 'agenda.hasta', N'To:'),
    ('en', 'agenda.hora', N'Time'),
    ('en', 'agenda.motivoRechazo', N'Rejection reason'),
    ('en', 'agenda.reasignacionOk', N'Reassignment completed. Logged notifications:'),
    ('en', 'agenda.rechazar', N'Reject'),
    ('en', 'agenda.selSugerencia', N'Select a suggestion from the list.'),
    ('en', 'agenda.sinMedicos', N'No enabled physicians; contact your administrator.'),
    ('en', 'agenda.sinTurnos', N'No appointments in the selected period.'),
    ('en', 'agenda.sug.columna.a', N'To (critical)'),
    ('en', 'agenda.sug.columna.de', N'From (stable)'),
    ('en', 'agenda.sugerencias', N'Reassignment suggestions'),
    ('en', 'agenda.sugerenciasVacias', N'No suggestions right now.'),
    ('en', 'app.nombre', N'OpenRIN'),
    ('en', 'app.titulo', N'Integrated Alerts and Monitoring Platform'),
    ('en', 'comun.aceptar', N'OK'),
    ('en', 'comun.buscar', N'Search'),
    ('en', 'comun.cancelar', N'Cancel'),
    ('en', 'comun.cargando', N'Loading...'),
    ('en', 'comun.cerrar', N'Close'),
    ('en', 'comun.eliminar', N'Delete'),
    ('en', 'comun.guardar', N'Save'),
    ('en', 'comun.modificar', N'Edit'),
    ('en', 'comun.no', N'No'),
    ('en', 'comun.nuevo', N'New'),
    ('en', 'comun.salir', N'Exit'),
    ('en', 'comun.si', N'Yes'),
    ('en', 'comun.volver', N'Back'),
    ('en', 'error.contacto', N'If the problem persists, contact your system administrator.'),
    ('en', 'error.generico', N'An unexpected error occurred. The operation could not be completed.'),
    ('en', 'error.titulo', N'Error'),
    ('en', 'eventos.columna.accion', N'Action taken'),
    ('en', 'eventos.columna.gravedad', N'Severity'),
    ('en', 'eventos.columna.tipo', N'Event type'),
    ('en', 'eventos.fechaEvento', N'Event date'),
    ('en', 'eventos.gravedad.grave', N'Severe'),
    ('en', 'eventos.gravedad.leve', N'Mild'),
    ('en', 'eventos.gravedad.moderada', N'Moderate'),
    ('en', 'eventos.recientes', N'Recent events'),
    ('en', 'eventos.registrar', N'Log adverse event'),
    ('en', 'eventos.selPaciente', N'Search for a patient to log an event.'),
    ('en', 'eventos.sinEventos', N'No events recorded.'),
    ('en', 'eventos.tipo.hemorragia', N'Bleeding'),
    ('en', 'eventos.tipo.otro', N'Other'),
    ('en', 'eventos.tipo.reaccion', N'Adverse reaction'),
    ('en', 'eventos.tipo.trombosis', N'Thrombosis'),
    ('en', 'hc.diagnostico', N'Diagnosis / indication'),
    ('en', 'hc.dosis', N'Dosage'),
    ('en', 'hc.limiteInferior', N'INR lower limit'),
    ('en', 'hc.limiteSuperior', N'INR upper limit'),
    ('en', 'hc.medicamento', N'Medication'),
    ('en', 'hc.periodicidad', N'Reporting interval (days)'),
    ('en', 'hc.proximoControl', N'Schedule next visit'),
    ('en', 'hc.sinConfigurar', N'No clinical record configured yet.'),
    ('en', 'hc.sinDiagnostico', N'(No diagnosis)'),
    ('en', 'hc.soloLectura', N'Read-only view: your profile cannot edit the clinical record.'),
    ('en', 'hc.titulo', N'Hematology Clinical Record'),
    ('en', 'idioma.en', N'English (United States)'),
    ('en', 'idioma.es', N'Español (Latinoamérica)'),
    ('en', 'idioma.zh-CN', N'中文（简体）'),
    ('en', 'idiomas.agregar', N'Add entry'),
    ('en', 'idiomas.clave', N'Key'),
    ('en', 'idiomas.claveObligatoria', N'Enter the entry key.'),
    ('en', 'idiomas.codigo', N'Code:'),
    ('en', 'idiomas.confirmarEliminar', N'Delete the selected language and all of its entries?'),
    ('en', 'idiomas.eliminar', N'Delete language'),
    ('en', 'idiomas.guardadoOk', N'Changes saved. Views were refreshed live.'),
    ('en', 'idiomas.guardar', N'Save changes'),
    ('en', 'idiomas.nombre', N'Name:'),
    ('en', 'idiomas.nuevo', N'New language'),
    ('en', 'idiomas.sinSeleccion', N'Select a language.'),
    ('en', 'idiomas.valor', N'Value'),
    ('en', 'integridad.alerta', N'⚠ Integrity:'),
    ('en', 'integridad.mensaje', N'Data integrity problems were detected in the database:'),
    ('en', 'integridad.ok', N'🛡️ Integrity OK'),
    ('en', 'integridad.titulo', N'Data integrity'),
    ('en', 'integridad.vulnerada.detalle', N'Technical detail of the verification:'),
    ('en', 'integridad.vulnerada.mensaje', N'The integrity check detected alterations to the database made from outside the system. Access has been blocked and the administrator must be contacted urgently.'),
    ('en', 'integridad.vulnerada.salir', N'Exit'),
    ('en', 'integridad.vulnerada.sinConexion', N'The integrity check could not be executed (database unreachable?). Contact the administrator.'),
    ('en', 'integridad.vulnerada.titulo', N'Database compromised'),
    ('en', 'login.bienvenida', N'Welcome'),
    ('en', 'login.campoObligatorio', N'Please enter your username and password.'),
    ('en', 'login.contrasena', N'Password'),
    ('en', 'login.errorBloqueado', N'Account temporarily locked for security.'),
    ('en', 'login.errorCredenciales', N'Incorrect username or password.'),
    ('en', 'login.errorInhabilitado', N'This user is disabled. Contact your administrator.'),
    ('en', 'login.idioma', N'Language'),
    ('en', 'login.ingresar', N'Sign In'),
    ('en', 'login.olvidoContrasena', N'Forgot your password?'),
    ('en', 'login.recuperar.enviar', N'Validate answer'),
    ('en', 'login.recuperar.respuesta', N'Security answer'),
    ('en', 'login.recuperar.titulo', N'Recover Password'),
    ('en', 'login.titulo', N'Sign In'),
    ('en', 'login.usuario', N'Username'),
    ('en', 'mod.agenda', N'Schedule & Appointments'),
    ('en', 'mod.eventos', N'Adverse Events'),
    ('en', 'mod.pacientes', N'Patients & Clinical Records'),
    ('en', 'mod.portal', N'Patient Portal'),
    ('en', 'mod.reportes', N'Reports'),
    ('en', 'mod.rin', N'INR Intake'),
    ('en', 'mod.seguimiento', N'Clinical Follow-up'),
    ('en', 'mod.sistema', N'System & Audit Log'),
    ('en', 'pacientes.alta', N'New Patient'),
    ('en', 'pacientes.baja', N'Deactivate'),
    ('en', 'pacientes.baja.confirmar', N'Confirm deactivation of ''{0}''? Portal credentials will be disabled (clinical history is preserved).'),
    ('en', 'pacientes.baja.motivo', N'Deactivation reason'),
    ('en', 'pacientes.buscar', N'Search:'),
    ('en', 'pacientes.buscarPlaceholder', N'Name or ID...'),
    ('en', 'pacientes.cred.aviso', N'Give these credentials to the patient. The temporary password will not be shown again.'),
    ('en', 'pacientes.cred.copiado', N'Password copied to clipboard.'),
    ('en', 'pacientes.cred.copiar', N'Copy password'),
    ('en', 'pacientes.cred.titulo', N'Portal credentials generated'),
    ('en', 'pacientes.documento', N'ID Document (DNI)'),
    ('en', 'pacientes.email', N'Email'),
    ('en', 'pacientes.estado', N'Status'),
    ('en', 'pacientes.estadoActivo', N'Active'),
    ('en', 'pacientes.estadoInactivo', N'Inactive'),
    ('en', 'pacientes.fechaAlta', N'Registered on'),
    ('en', 'pacientes.historia', N'Clinical record'),
    ('en', 'pacientes.nombre', N'Full name'),
    ('en', 'pacientes.numeroAfiliado', N'Member number'),
    ('en', 'pacientes.obraSocial', N'Health insurance'),
    ('en', 'pacientes.resultados', N'{0} patient(s) found'),
    ('en', 'pacientes.sinObraSocial', N'(No insurance)'),
    ('en', 'pacientes.sinSeleccion', N'Select a patient from the list.'),
    ('en', 'pacientes.telefono', N'Phone'),
    ('en', 'pacientes.titulo', N'Patient Management'),
    ('en', 'pacientes.verInactivos', N'Show inactive'),
    ('en', 'panel.actualizar', N'Refresh'),
    ('en', 'panel.columna.alerta', N'Alert'),
    ('en', 'panel.columna.criticidad', N'Criticality'),
    ('en', 'panel.columna.dias', N'Days since report'),
    ('en', 'panel.columna.documento', N'ID Document'),
    ('en', 'panel.columna.fecha', N'Last report'),
    ('en', 'panel.columna.paciente', N'Patient'),
    ('en', 'panel.columna.ultimoRin', N'Latest INR'),
    ('en', 'panel.criticidadAlta', N'Critical (High)'),
    ('en', 'panel.criticidadBaja', N'Stable (Low)'),
    ('en', 'panel.criticidadMedia', N'Moderate (Medium)'),
    ('en', 'panel.leyenda', N'Legend:'),
    ('en', 'panel.refresco', N'Updated:'),
    ('en', 'panel.sinDatos', N'No data'),
    ('en', 'panel.titulo', N'Monitoring Dashboard'),
    ('en', 'portal.bienvenida', N'Hello,'),
    ('en', 'portal.enviar', N'Send report'),
    ('en', 'portal.gracias', N'Thank you! Your report has been recorded.'),
    ('en', 'portal.historial', N'My clinical history'),
    ('en', 'portal.notificado', N'The medical team has been notified and will review your case.'),
    ('en', 'portal.reportar', N'Report my INR'),
    ('en', 'portal.sinVinculo', N'Your account is not linked to a patient record. Please contact the administration.'),
    ('en', 'rec.cambiar', N'Change password'),
    ('en', 'rec.nuevaContrasena', N'New password'),
    ('en', 'rec.ok', N'Done! The password was updated. You can now sign in with the new one.'),
    ('en', 'rec.pregunta', N'Security question:'),
    ('en', 'rec.pregunta1', N'Which city did you grow up in?'),
    ('en', 'rec.pregunta2', N'Name of your first pet?'),
    ('en', 'rec.pregunta3', N'Name of your primary school?'),
    ('en', 'rec.respuesta', N'Answer'),
    ('en', 'rec.sinPregunta', N'A security question could not be retrieved for that user. Please contact the administrator.'),
    ('en', 'rec.titulo', N'Password recovery'),
    ('en', 'rec.verPregunta', N'Show security question'),
    ('en', 'reportes.bajoDesempeno', N'⚠ LOW PERFORMANCE'),
    ('en', 'reportes.clas.deficiente', N'Deficient'),
    ('en', 'reportes.clas.optimo', N'Optimal'),
    ('en', 'reportes.clas.suboptimo', N'Suboptimal'),
    ('en', 'reportes.columna.clasificacion', N'Classification'),
    ('en', 'reportes.columna.descripcion', N'Description'),
    ('en', 'reportes.columna.diagnostico', N'Diagnosis'),
    ('en', 'reportes.columna.indicador', N'Avg. indicator (%)'),
    ('en', 'reportes.columna.mediciones', N'Measurements'),
    ('en', 'reportes.columna.pacientes', N'Patients'),
    ('en', 'reportes.columna.porcentaje', N'% in range'),
    ('en', 'reportes.columna.tipo', N'Type'),
    ('en', 'reportes.diagnostico', N'By diagnosis'),
    ('en', 'reportes.exportadoOk', N'Export logged. File generated:'),
    ('en', 'reportes.exportar', N'Export history'),
    ('en', 'reportes.formato', N'Format:'),
    ('en', 'reportes.generar', N'View monthly report'),
    ('en', 'reportes.generarDiag', N'Generate report'),
    ('en', 'reportes.historial', N'Patient history'),
    ('en', 'reportes.historialVacio', N'Search for a patient to view their unified history.'),
    ('en', 'reportes.indicadorGlobal', N'Global efficacy indicator'),
    ('en', 'reportes.mensual', N'Monthly report'),
    ('en', 'reportes.pacientesDatos', N'Patients with data:'),
    ('en', 'reportes.periodo', N'Period:'),
    ('en', 'reportes.sinItems', N'no records yet'),
    ('en', 'reportes.sinMediciones', N'No measurements:'),
    ('en', 'reportes.sinReporte', N'Generate the monthly report to see the indicators.'),
    ('en', 'rin.alertaGenerada', N'🔔 Urgent alert generated and notified (physician and administrative staff).'),
    ('en', 'rin.canal', N'Report channel'),
    ('en', 'rin.canal.digital', N'Digital (portal)'),
    ('en', 'rin.canal.telefonico', N'Phone (manual entry)'),
    ('en', 'rin.columna.canal', N'Channel'),
    ('en', 'rin.columna.fecha', N'Date'),
    ('en', 'rin.columna.valor', N'Value'),
    ('en', 'rin.enviado', N'Your INR was reported successfully.'),
    ('en', 'rin.fecha', N'Measurement date'),
    ('en', 'rin.historial', N'Recent measurements'),
    ('en', 'rin.identificacion', N'Patient identification (ID):'),
    ('en', 'rin.pacienteInactivo', N'The patient is deactivated; no new reports allowed.'),
    ('en', 'rin.pacienteNoEncontrado', N'No patient found with that ID.'),
    ('en', 'rin.rango', N'Therapeutic range'),
    ('en', 'rin.reportar', N'Report INR'),
    ('en', 'rin.resultado', N'Triage result'),
    ('en', 'rin.resultadoSinDatos', N'Search a patient and enter an INR value.'),
    ('en', 'rin.sinHistoria', N'The patient has no clinical record configured (required for triage).'),
    ('en', 'rin.sinMediciones', N'No previous measurements.'),
    ('en', 'rin.tendencia', N'⚠ Reclassified due to dangerous trend (±0.1 in two consecutive reports).'),
    ('en', 'rin.ultimaMedicion', N'Last measurement'),
    ('en', 'rin.valor', N'INR value'),
    ('en', 'seguimiento.columna.decision', N'Decision'),
    ('en', 'seguimiento.columna.diasVencido', N'Days overdue'),
    ('en', 'seguimiento.columna.intentos', N'Attempts'),
    ('en', 'seguimiento.columna.protocolo', N'Protocol'),
    ('en', 'seguimiento.columna.ultimoReporte', N'Last report'),
    ('en', 'seguimiento.contacto', N'Log contact attempt'),
    ('en', 'seguimiento.contacto.correo', N'Email'),
    ('en', 'seguimiento.contacto.llamado', N'Phone call'),
    ('en', 'seguimiento.contacto.mensaje', N'Text message'),
    ('en', 'seguimiento.contacto.otro', N'Other'),
    ('en', 'seguimiento.contactoOk', N'Successful contact: the absence alert was closed.'),
    ('en', 'seguimiento.dec.contactar', N'Contact personally'),
    ('en', 'seguimiento.dec.nocontactable', N'Declare unreachable'),
    ('en', 'seguimiento.dec.periodicidad', N'Change reporting frequency'),
    ('en', 'seguimiento.dec.visita', N'Schedule home visit'),
    ('en', 'seguimiento.decSinIntentos', N'The clinical decision requires at least one logged contact attempt.'),
    ('en', 'seguimiento.decision', N'Clinical decision'),
    ('en', 'seguimiento.decisionOk', N'Decision logged; the absence alert was resolved.'),
    ('en', 'seguimiento.detalleDecision', N'Decision detail'),
    ('en', 'seguimiento.detalleVacio', N'Select a case from the list.'),
    ('en', 'seguimiento.deteccion', N'Detection completed. New cases:'),
    ('en', 'seguimiento.detectar', N'Detect overdue cases'),
    ('en', 'seguimiento.escalada', N'Escalated to physician'),
    ('en', 'seguimiento.escaladaMsg', N'The threshold of 3 failed attempts was reached: the case was ESCALATED to the physician for a clinical decision.'),
    ('en', 'seguimiento.historial', N'Case history'),
    ('en', 'seguimiento.intentoRegistrado', N'Attempt logged.'),
    ('en', 'seguimiento.nuevaPeriodicidad', N'New frequency (days)'),
    ('en', 'seguimiento.protocolo.enCurso', N'In progress'),
    ('en', 'seguimiento.protocolo.escalada', N'ESCALATED TO PHYSICIAN'),
    ('en', 'seguimiento.registrarDecision', N'Log decision'),
    ('en', 'seguimiento.registrarIntento', N'Log attempt'),
    ('en', 'seguimiento.resultado', N'Result'),
    ('en', 'seguimiento.resultado.exitoso', N'Successful (closes the alert)'),
    ('en', 'seguimiento.resultado.fallido', N'Failed (counts attempt)'),
    ('en', 'seguimiento.sinPendientes', N'No pending follow-ups. Use “Detect overdue cases” to scan for new ones.'),
    ('en', 'seguimiento.tipoContacto', N'Contact type'),
    ('en', 'shell.cerrarSesion', N'Sign out'),
    ('en', 'shell.confirmarCerrar', N'Do you want to sign out?'),
    ('en', 'shell.enConstruccion', N'Module under construction; it will be available in the next milestone.'),
    ('en', 'shell.modulos', N'Modules'),
    ('en', 'shell.seleccione', N'Select a module from the side menu to begin.'),
    ('en', 'shell.sesion', N'Session:'),
    ('en', 'shell.titulo', N'Main Panel'),
    ('en', 'sistema.actualizar', N'Refresh'),
    ('en', 'sistema.bitacora', N'Activity log'),
    ('en', 'sistema.cambios', N'Change control'),
    ('en', 'sistema.cambios.anterior', N'Previous state (JSON)'),
    ('en', 'sistema.cambios.buscar', N'Search history'),
    ('en', 'sistema.cambios.columna.entidad', N'Entity'),
    ('en', 'sistema.cambios.columna.registro', N'Record'),
    ('en', 'sistema.cambios.columna.tipo', N'Type'),
    ('en', 'sistema.cambios.confirmar', N'Restore the previous state of the selected record?'),
    ('en', 'sistema.cambios.entidad', N'Entity:'),
    ('en', 'sistema.cambios.idRegistro', N'Record no.:'),
    ('en', 'sistema.cambios.nuevo', N'New state (JSON)'),
    ('en', 'sistema.cambios.restaurar', N'Restore previous state'),
    ('en', 'sistema.cambios.selCambio', N'Select a change from the history.'),
    ('en', 'sistema.cambios.sinId', N'The record number must be numeric.'),
    ('en', 'sistema.cambios.todas', N'All entities'),
    ('en', 'sistema.columna.activo', N'Active'),
    ('en', 'sistema.columna.bloqueado', N'Locked until'),
    ('en', 'sistema.columna.capa', N'Layer'),
    ('en', 'sistema.columna.intentos', N'Attempts'),
    ('en', 'sistema.columna.mensaje', N'Message'),
    ('en', 'sistema.columna.nivel', N'Level'),
    ('en', 'sistema.columna.nombre', N'Full name'),
    ('en', 'sistema.columna.perfil', N'Profile'),
    ('en', 'sistema.columna.usuario', N'Username'),
    ('en', 'sistema.confirmarDeshabilitar', N'Disable the selected user''s credentials?'),
    ('en', 'sistema.confirmarHabilitar', N'Enable the selected user''s credentials?'),
    ('en', 'sistema.deshabilitar', N'Disable'),
    ('en', 'sistema.habilitar', N'Enable'),
    ('en', 'sistema.idiomas', N'Languages'),
    ('en', 'sistema.nivel', N'Minimum level:'),
    ('en', 'sistema.nivel.todos', N'All'),
    ('en', 'sistema.no', N'No'),
    ('en', 'sistema.nuevoUsuario', N'New user'),
    ('en', 'sistema.selUsuario', N'Select a user from the list.'),
    ('en', 'sistema.si', N'Yes'),
    ('en', 'sistema.usuarioRegistrado', N'User created successfully.'),
    ('en', 'sistema.usuarios', N'Users')
) AS origen(CodigoIdioma, Clave, Valor)
ON destino.CodigoIdioma = origen.CodigoIdioma AND destino.Clave = origen.Clave
WHEN MATCHED THEN UPDATE SET Valor = origen.Valor
WHEN NOT MATCHED THEN INSERT (CodigoIdioma, Clave, Valor)
    VALUES (origen.CodigoIdioma, origen.Clave, origen.Valor);
GO

-- Idioma zh-CN: 303 claves
MERGE dbo.Textos AS destino
USING (VALUES
    ('zh-CN', 'agenda.actualizar', N'刷新日程'),
    ('zh-CN', 'agenda.agendar', N'预约挂号'),
    ('zh-CN', 'agenda.columna.fechaHora', N'日期时间'),
    ('zh-CN', 'agenda.columna.medico', N'医生'),
    ('zh-CN', 'agenda.columna.observaciones', N'备注'),
    ('zh-CN', 'agenda.desde', N'从：'),
    ('zh-CN', 'agenda.escalar', N'是否将决定上报给医生？（因临床疑虑拒绝）'),
    ('zh-CN', 'agenda.estado.atendido', N'已就诊'),
    ('zh-CN', 'agenda.estado.cancelado', N'已取消'),
    ('zh-CN', 'agenda.estado.confirmado', N'已确认'),
    ('zh-CN', 'agenda.estado.pendiente', N'待定'),
    ('zh-CN', 'agenda.estado.reasignacion', N'重新分配中'),
    ('zh-CN', 'agenda.hasta', N'至：'),
    ('zh-CN', 'agenda.hora', N'时间'),
    ('zh-CN', 'agenda.motivoRechazo', N'拒绝原因'),
    ('zh-CN', 'agenda.reasignacionOk', N'重新分配完成。已记录通知：'),
    ('zh-CN', 'agenda.rechazar', N'拒绝'),
    ('zh-CN', 'agenda.selSugerencia', N'请从列表中选择一条建议。'),
    ('zh-CN', 'agenda.sinMedicos', N'没有可用的医生，请联系管理员。'),
    ('zh-CN', 'agenda.sinTurnos', N'所选时段内暂无预约。'),
    ('zh-CN', 'agenda.sug.columna.a', N'转给（高危）'),
    ('zh-CN', 'agenda.sug.columna.de', N'来自（稳定）'),
    ('zh-CN', 'agenda.sugerencias', N'重新分配建议'),
    ('zh-CN', 'agenda.sugerenciasVacias', N'暂无建议。'),
    ('zh-CN', 'app.nombre', N'OpenRIN'),
    ('zh-CN', 'app.titulo', N'警报与监测综合平台'),
    ('zh-CN', 'comun.aceptar', N'确定'),
    ('zh-CN', 'comun.buscar', N'搜索'),
    ('zh-CN', 'comun.cancelar', N'取消'),
    ('zh-CN', 'comun.cargando', N'加载中……'),
    ('zh-CN', 'comun.cerrar', N'关闭'),
    ('zh-CN', 'comun.eliminar', N'删除'),
    ('zh-CN', 'comun.guardar', N'保存'),
    ('zh-CN', 'comun.modificar', N'修改'),
    ('zh-CN', 'comun.no', N'否'),
    ('zh-CN', 'comun.nuevo', N'新建'),
    ('zh-CN', 'comun.salir', N'退出'),
    ('zh-CN', 'comun.si', N'是'),
    ('zh-CN', 'comun.volver', N'返回'),
    ('zh-CN', 'error.contacto', N'如果问题持续存在，请联系系统管理员。'),
    ('zh-CN', 'error.generico', N'发生意外错误，操作未能完成。'),
    ('zh-CN', 'error.titulo', N'错误'),
    ('zh-CN', 'eventos.columna.accion', N'已采取措施'),
    ('zh-CN', 'eventos.columna.gravedad', N'严重程度'),
    ('zh-CN', 'eventos.columna.tipo', N'事件类型'),
    ('zh-CN', 'eventos.fechaEvento', N'事件日期'),
    ('zh-CN', 'eventos.gravedad.grave', N'重度'),
    ('zh-CN', 'eventos.gravedad.leve', N'轻度'),
    ('zh-CN', 'eventos.gravedad.moderada', N'中度'),
    ('zh-CN', 'eventos.recientes', N'最近事件'),
    ('zh-CN', 'eventos.registrar', N'登记不良事件'),
    ('zh-CN', 'eventos.selPaciente', N'请先搜索患者再登记事件。'),
    ('zh-CN', 'eventos.sinEventos', N'暂无已登记事件。'),
    ('zh-CN', 'eventos.tipo.hemorragia', N'出血'),
    ('zh-CN', 'eventos.tipo.otro', N'其他'),
    ('zh-CN', 'eventos.tipo.reaccion', N'不良反应'),
    ('zh-CN', 'eventos.tipo.trombosis', N'血栓形成'),
    ('zh-CN', 'hc.diagnostico', N'诊断/适应症'),
    ('zh-CN', 'hc.dosis', N'剂量'),
    ('zh-CN', 'hc.limiteInferior', N'INR 下限'),
    ('zh-CN', 'hc.limiteSuperior', N'INR 上限'),
    ('zh-CN', 'hc.medicamento', N'药物'),
    ('zh-CN', 'hc.periodicidad', N'报告周期（天）'),
    ('zh-CN', 'hc.proximoControl', N'安排下次复诊'),
    ('zh-CN', 'hc.sinConfigurar', N'该患者尚未配置病历。'),
    ('zh-CN', 'hc.sinDiagnostico', N'（无诊断）'),
    ('zh-CN', 'hc.soloLectura', N'只读视图：您的角色无法修改病历。'),
    ('zh-CN', 'hc.titulo', N'血液科病历'),
    ('zh-CN', 'idioma.en', N'English (United States)'),
    ('zh-CN', 'idioma.es', N'Español (Latinoamérica)'),
    ('zh-CN', 'idioma.zh-CN', N'中文（简体）'),
    ('zh-CN', 'idiomas.agregar', N'添加词条'),
    ('zh-CN', 'idiomas.clave', N'键'),
    ('zh-CN', 'idiomas.claveObligatoria', N'请输入词条键。'),
    ('zh-CN', 'idiomas.codigo', N'代码：'),
    ('zh-CN', 'idiomas.confirmarEliminar', N'是否删除所选语言及其全部词条？'),
    ('zh-CN', 'idiomas.eliminar', N'删除语言'),
    ('zh-CN', 'idiomas.guardadoOk', N'更改已保存，视图已实时更新。'),
    ('zh-CN', 'idiomas.guardar', N'保存更改'),
    ('zh-CN', 'idiomas.nombre', N'名称：'),
    ('zh-CN', 'idiomas.nuevo', N'新建语言'),
    ('zh-CN', 'idiomas.sinSeleccion', N'请选择语言。'),
    ('zh-CN', 'idiomas.valor', N'值'),
    ('zh-CN', 'integridad.alerta', N'⚠ 完整性：'),
    ('zh-CN', 'integridad.mensaje', N'检测到数据库完整性问题：'),
    ('zh-CN', 'integridad.ok', N'🛡️ 完整性正常'),
    ('zh-CN', 'integridad.titulo', N'数据完整性'),
    ('zh-CN', 'integridad.vulnerada.detalle', N'校验技术详情：'),
    ('zh-CN', 'integridad.vulnerada.mensaje', N'完整性校验检测到数据库被系统外部修改。访问已被阻止，请紧急联系管理员。'),
    ('zh-CN', 'integridad.vulnerada.salir', N'退出'),
    ('zh-CN', 'integridad.vulnerada.sinConexion', N'无法执行完整性校验（数据库不可访问？）。请联系管理员。'),
    ('zh-CN', 'integridad.vulnerada.titulo', N'数据库已被篡改'),
    ('zh-CN', 'login.bienvenida', N'欢迎'),
    ('zh-CN', 'login.campoObligatorio', N'请输入用户名和密码。'),
    ('zh-CN', 'login.contrasena', N'密码'),
    ('zh-CN', 'login.errorBloqueado', N'账户因安全原因已被临时锁定。'),
    ('zh-CN', 'login.errorCredenciales', N'用户名或密码错误。'),
    ('zh-CN', 'login.errorInhabilitado', N'该用户已被停用，请联系管理员。'),
    ('zh-CN', 'login.idioma', N'语言'),
    ('zh-CN', 'login.ingresar', N'登录'),
    ('zh-CN', 'login.olvidoContrasena', N'忘记密码？'),
    ('zh-CN', 'login.recuperar.enviar', N'验证答案'),
    ('zh-CN', 'login.recuperar.respuesta', N'安全问题答案'),
    ('zh-CN', 'login.recuperar.titulo', N'找回密码'),
    ('zh-CN', 'login.titulo', N'登录'),
    ('zh-CN', 'login.usuario', N'用户名'),
    ('zh-CN', 'mod.agenda', N'日程与预约'),
    ('zh-CN', 'mod.eventos', N'不良事件'),
    ('zh-CN', 'mod.pacientes', N'患者与病历'),
    ('zh-CN', 'mod.portal', N'患者门户'),
    ('zh-CN', 'mod.reportes', N'报告'),
    ('zh-CN', 'mod.rin', N'INR 接收'),
    ('zh-CN', 'mod.seguimiento', N'临床随访'),
    ('zh-CN', 'mod.sistema', N'系统与日志'),
    ('zh-CN', 'pacientes.alta', N'新增患者'),
    ('zh-CN', 'pacientes.baja', N'停用患者'),
    ('zh-CN', 'pacientes.baja.confirmar', N'确认停用“{0}”？其门户凭据将被禁用（病历将保留）。'),
    ('zh-CN', 'pacientes.baja.motivo', N'停用原因'),
    ('zh-CN', 'pacientes.buscar', N'搜索：'),
    ('zh-CN', 'pacientes.buscarPlaceholder', N'姓名或证件…'),
    ('zh-CN', 'pacientes.cred.aviso', N'请将凭据交给患者。临时密码不会再次显示。'),
    ('zh-CN', 'pacientes.cred.copiado', N'密码已复制到剪贴板。'),
    ('zh-CN', 'pacientes.cred.copiar', N'复制密码'),
    ('zh-CN', 'pacientes.cred.titulo', N'门户凭据已生成'),
    ('zh-CN', 'pacientes.documento', N'证件号码（DNI）'),
    ('zh-CN', 'pacientes.email', N'电子邮箱'),
    ('zh-CN', 'pacientes.estado', N'状态'),
    ('zh-CN', 'pacientes.estadoActivo', N'已启用'),
    ('zh-CN', 'pacientes.estadoInactivo', N'已停用'),
    ('zh-CN', 'pacientes.fechaAlta', N'登记日期'),
    ('zh-CN', 'pacientes.historia', N'病历'),
    ('zh-CN', 'pacientes.nombre', N'姓名'),
    ('zh-CN', 'pacientes.numeroAfiliado', N'参保编号'),
    ('zh-CN', 'pacientes.obraSocial', N'医疗保险'),
    ('zh-CN', 'pacientes.resultados', N'找到 {0} 位患者'),
    ('zh-CN', 'pacientes.sinObraSocial', N'（无医保）'),
    ('zh-CN', 'pacientes.sinSeleccion', N'请先从列表中选择患者。'),
    ('zh-CN', 'pacientes.telefono', N'电话'),
    ('zh-CN', 'pacientes.titulo', N'患者管理'),
    ('zh-CN', 'pacientes.verInactivos', N'显示已停用'),
    ('zh-CN', 'panel.actualizar', N'刷新'),
    ('zh-CN', 'panel.columna.alerta', N'警报'),
    ('zh-CN', 'panel.columna.criticidad', N'危急程度'),
    ('zh-CN', 'panel.columna.dias', N'距上次报告天数'),
    ('zh-CN', 'panel.columna.documento', N'证件'),
    ('zh-CN', 'panel.columna.fecha', N'最近报告'),
    ('zh-CN', 'panel.columna.paciente', N'患者'),
    ('zh-CN', 'panel.columna.ultimoRin', N'最新 INR'),
    ('zh-CN', 'panel.criticidadAlta', N'高危'),
    ('zh-CN', 'panel.criticidadBaja', N'低危'),
    ('zh-CN', 'panel.criticidadMedia', N'中危'),
    ('zh-CN', 'panel.leyenda', N'图例：'),
    ('zh-CN', 'panel.refresco', N'已更新：'),
    ('zh-CN', 'panel.sinDatos', N'无数据'),
    ('zh-CN', 'panel.titulo', N'监控面板'),
    ('zh-CN', 'portal.bienvenida', N'你好，'),
    ('zh-CN', 'portal.enviar', N'提交报告'),
    ('zh-CN', 'portal.gracias', N'谢谢！您的报告已登记。'),
    ('zh-CN', 'portal.historial', N'我的病历'),
    ('zh-CN', 'portal.notificado', N'医疗团队已收到通知并将审核您的情况。'),
    ('zh-CN', 'portal.reportar', N'报告我的 INR'),
    ('zh-CN', 'portal.sinVinculo', N'您的账户尚未关联患者档案，请联系管理人员。'),
    ('zh-CN', 'rec.cambiar', N'更改密码'),
    ('zh-CN', 'rec.nuevaContrasena', N'新密码'),
    ('zh-CN', 'rec.ok', N'完成！密码已更新，请使用新密码登录。'),
    ('zh-CN', 'rec.pregunta', N'安全问题：'),
    ('zh-CN', 'rec.pregunta1', N'您成长的城市？'),
    ('zh-CN', 'rec.pregunta2', N'您第一只宠物的名字？'),
    ('zh-CN', 'rec.pregunta3', N'您小学的名字？'),
    ('zh-CN', 'rec.respuesta', N'答案'),
    ('zh-CN', 'rec.sinPregunta', N'无法获取该用户的安全问题，请联系管理员。'),
    ('zh-CN', 'rec.titulo', N'密码找回'),
    ('zh-CN', 'rec.verPregunta', N'查看安全问题'),
    ('zh-CN', 'reportes.bajoDesempeno', N'⚠ 表现不足'),
    ('zh-CN', 'reportes.clas.deficiente', N'欠佳'),
    ('zh-CN', 'reportes.clas.optimo', N'最优'),
    ('zh-CN', 'reportes.clas.suboptimo', N'次优'),
    ('zh-CN', 'reportes.columna.clasificacion', N'分类'),
    ('zh-CN', 'reportes.columna.descripcion', N'描述'),
    ('zh-CN', 'reportes.columna.diagnostico', N'诊断'),
    ('zh-CN', 'reportes.columna.indicador', N'平均指标（%）'),
    ('zh-CN', 'reportes.columna.mediciones', N'测量次数'),
    ('zh-CN', 'reportes.columna.pacientes', N'患者数'),
    ('zh-CN', 'reportes.columna.porcentaje', N'范围内占比'),
    ('zh-CN', 'reportes.columna.tipo', N'类型'),
    ('zh-CN', 'reportes.diagnostico', N'按诊断'),
    ('zh-CN', 'reportes.exportadoOk', N'导出已记录。文件已生成：'),
    ('zh-CN', 'reportes.exportar', N'导出病史'),
    ('zh-CN', 'reportes.formato', N'格式：'),
    ('zh-CN', 'reportes.generar', N'查看月度报告'),
    ('zh-CN', 'reportes.generarDiag', N'生成报告'),
    ('zh-CN', 'reportes.historial', N'患者病史'),
    ('zh-CN', 'reportes.historialVacio', N'请搜索患者以查看统一病史。'),
    ('zh-CN', 'reportes.indicadorGlobal', N'总体疗效指标'),
    ('zh-CN', 'reportes.mensual', N'月度报告'),
    ('zh-CN', 'reportes.pacientesDatos', N'有数据患者：'),
    ('zh-CN', 'reportes.periodo', N'期间：'),
    ('zh-CN', 'reportes.sinItems', N'暂无记录'),
    ('zh-CN', 'reportes.sinMediciones', N'无测量：'),
    ('zh-CN', 'reportes.sinReporte', N'请先生成月度报告以查看指标。'),
    ('zh-CN', 'rin.alertaGenerada', N'🔔 已生成并通知紧急警报（医生与管理员）。'),
    ('zh-CN', 'rin.canal', N'报告渠道'),
    ('zh-CN', 'rin.canal.digital', N'数字（门户）'),
    ('zh-CN', 'rin.canal.telefonico', N'电话（人工录入）'),
    ('zh-CN', 'rin.columna.canal', N'渠道'),
    ('zh-CN', 'rin.columna.fecha', N'日期'),
    ('zh-CN', 'rin.columna.valor', N'数值'),
    ('zh-CN', 'rin.enviado', N'您的 INR 已成功上报。'),
    ('zh-CN', 'rin.fecha', N'测量日期'),
    ('zh-CN', 'rin.historial', N'最近测量记录'),
    ('zh-CN', 'rin.identificacion', N'患者身份（证件号码）：'),
    ('zh-CN', 'rin.pacienteInactivo', N'患者已停用，无法新增报告。'),
    ('zh-CN', 'rin.pacienteNoEncontrado', N'未找到该证件号码的患者。'),
    ('zh-CN', 'rin.rango', N'治疗范围'),
    ('zh-CN', 'rin.reportar', N'报告 INR'),
    ('zh-CN', 'rin.resultado', N'分级结果'),
    ('zh-CN', 'rin.resultadoSinDatos', N'请先搜索患者并输入 INR 数值。'),
    ('zh-CN', 'rin.sinHistoria', N'患者尚未配置病历（分级所需）。'),
    ('zh-CN', 'rin.sinMediciones', N'暂无历史测量。'),
    ('zh-CN', 'rin.tendencia', N'⚠ 因危险趋势重新分级（连续两次报告处于 ±0.1 边界）。'),
    ('zh-CN', 'rin.ultimaMedicion', N'最近测量'),
    ('zh-CN', 'rin.valor', N'INR 数值'),
    ('zh-CN', 'seguimiento.columna.decision', N'决定'),
    ('zh-CN', 'seguimiento.columna.diasVencido', N'逾期天数'),
    ('zh-CN', 'seguimiento.columna.intentos', N'尝试次数'),
    ('zh-CN', 'seguimiento.columna.protocolo', N'随访状态'),
    ('zh-CN', 'seguimiento.columna.ultimoReporte', N'最近报告'),
    ('zh-CN', 'seguimiento.contacto', N'登记联系尝试'),
    ('zh-CN', 'seguimiento.contacto.correo', N'电子邮件'),
    ('zh-CN', 'seguimiento.contacto.llamado', N'电话'),
    ('zh-CN', 'seguimiento.contacto.mensaje', N'短信'),
    ('zh-CN', 'seguimiento.contacto.otro', N'其他'),
    ('zh-CN', 'seguimiento.contactoOk', N'联系成功：缺勤警报已关闭。'),
    ('zh-CN', 'seguimiento.dec.contactar', N'亲自联系'),
    ('zh-CN', 'seguimiento.dec.nocontactable', N'宣布无法联系'),
    ('zh-CN', 'seguimiento.dec.periodicidad', N'更改报告周期'),
    ('zh-CN', 'seguimiento.dec.visita', N'安排家访'),
    ('zh-CN', 'seguimiento.decSinIntentos', N'临床决定需要至少一次已登记的联系尝试。'),
    ('zh-CN', 'seguimiento.decision', N'临床决定'),
    ('zh-CN', 'seguimiento.decisionOk', N'决定已登记；缺勤警报已解决。'),
    ('zh-CN', 'seguimiento.detalleDecision', N'决定详情'),
    ('zh-CN', 'seguimiento.detalleVacio', N'请从列表中选择病例。'),
    ('zh-CN', 'seguimiento.deteccion', N'检测完成。新病例：'),
    ('zh-CN', 'seguimiento.detectar', N'检测逾期病例'),
    ('zh-CN', 'seguimiento.escalada', N'上报医生'),
    ('zh-CN', 'seguimiento.escaladaMsg', N'已达到 3 次失败尝试的阈值：病例已上报医生等待临床决定。'),
    ('zh-CN', 'seguimiento.historial', N'病例历史'),
    ('zh-CN', 'seguimiento.intentoRegistrado', N'尝试已登记。'),
    ('zh-CN', 'seguimiento.nuevaPeriodicidad', N'新周期（天）'),
    ('zh-CN', 'seguimiento.protocolo.enCurso', N'进行中'),
    ('zh-CN', 'seguimiento.protocolo.escalada', N'已上报医生'),
    ('zh-CN', 'seguimiento.registrarDecision', N'登记决定'),
    ('zh-CN', 'seguimiento.registrarIntento', N'登记尝试'),
    ('zh-CN', 'seguimiento.resultado', N'结果'),
    ('zh-CN', 'seguimiento.resultado.exitoso', N'成功（关闭警报）'),
    ('zh-CN', 'seguimiento.resultado.fallido', N'失败（计为尝试）'),
    ('zh-CN', 'seguimiento.sinPendientes', N'暂无待处理的随访。使用「检测逾期」查找新病例。'),
    ('zh-CN', 'seguimiento.tipoContacto', N'联系方式'),
    ('zh-CN', 'shell.cerrarSesion', N'退出登录'),
    ('zh-CN', 'shell.confirmarCerrar', N'您确定要退出当前登录吗？'),
    ('zh-CN', 'shell.enConstruccion', N'模块建设中，将在下一步更新中提供。'),
    ('zh-CN', 'shell.modulos', N'模块'),
    ('zh-CN', 'shell.seleccione', N'请从侧边菜单选择模块开始使用。'),
    ('zh-CN', 'shell.sesion', N'会话：'),
    ('zh-CN', 'shell.titulo', N'主面板'),
    ('zh-CN', 'sistema.actualizar', N'刷新'),
    ('zh-CN', 'sistema.bitacora', N'日志'),
    ('zh-CN', 'sistema.cambios', N'变更控制'),
    ('zh-CN', 'sistema.cambios.anterior', N'原状态（JSON）'),
    ('zh-CN', 'sistema.cambios.buscar', N'查询历史'),
    ('zh-CN', 'sistema.cambios.columna.entidad', N'实体'),
    ('zh-CN', 'sistema.cambios.columna.registro', N'记录'),
    ('zh-CN', 'sistema.cambios.columna.tipo', N'类型'),
    ('zh-CN', 'sistema.cambios.confirmar', N'是否恢复所选记录的原状态？'),
    ('zh-CN', 'sistema.cambios.entidad', N'实体：'),
    ('zh-CN', 'sistema.cambios.idRegistro', N'记录编号：'),
    ('zh-CN', 'sistema.cambios.nuevo', N'新状态（JSON）'),
    ('zh-CN', 'sistema.cambios.restaurar', N'恢复原状态'),
    ('zh-CN', 'sistema.cambios.selCambio', N'请从历史中选择一条变更。'),
    ('zh-CN', 'sistema.cambios.sinId', N'记录编号必须为数字。'),
    ('zh-CN', 'sistema.cambios.todas', N'所有实体'),
    ('zh-CN', 'sistema.columna.activo', N'启用状态'),
    ('zh-CN', 'sistema.columna.bloqueado', N'锁定至'),
    ('zh-CN', 'sistema.columna.capa', N'层'),
    ('zh-CN', 'sistema.columna.intentos', N'尝试次数'),
    ('zh-CN', 'sistema.columna.mensaje', N'消息'),
    ('zh-CN', 'sistema.columna.nivel', N'级别'),
    ('zh-CN', 'sistema.columna.nombre', N'姓名'),
    ('zh-CN', 'sistema.columna.perfil', N'角色'),
    ('zh-CN', 'sistema.columna.usuario', N'用户名'),
    ('zh-CN', 'sistema.confirmarDeshabilitar', N'是否停用所选用户的凭据？'),
    ('zh-CN', 'sistema.confirmarHabilitar', N'是否启用所选用户的凭据？'),
    ('zh-CN', 'sistema.deshabilitar', N'禁用'),
    ('zh-CN', 'sistema.habilitar', N'启用'),
    ('zh-CN', 'sistema.idiomas', N'语言'),
    ('zh-CN', 'sistema.nivel', N'最低级别：'),
    ('zh-CN', 'sistema.nivel.todos', N'全部'),
    ('zh-CN', 'sistema.no', N'否'),
    ('zh-CN', 'sistema.nuevoUsuario', N'新建用户'),
    ('zh-CN', 'sistema.selUsuario', N'请从列表中选择用户。'),
    ('zh-CN', 'sistema.si', N'是'),
    ('zh-CN', 'sistema.usuarioRegistrado', N'用户创建成功。'),
    ('zh-CN', 'sistema.usuarios', N'用户')
) AS origen(CodigoIdioma, Clave, Valor)
ON destino.CodigoIdioma = origen.CodigoIdioma AND destino.Clave = origen.Clave
WHEN MATCHED THEN UPDATE SET Valor = origen.Valor
WHEN NOT MATCHED THEN INSERT (CodigoIdioma, Clave, Valor)
    VALUES (origen.CodigoIdioma, origen.Clave, origen.Valor);
GO
